# Generated by Django 3.0.1 on 2020-03-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0004_auto_20200318_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('contents', models.TextField(verbose_name='内容')),
                ('createTime', models.DateTimeField(verbose_name='新建时间')),
                ('updateTime', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('upTimes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogOwner', to='backend.User', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='BlogUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upBlog', to='blogs.Blog', verbose_name='博客')),
                ('upUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='upUser', to='backend.User', verbose_name='点赞人')),
            ],
        ),
    ]
