# Generated by Django 3.0.1 on 2020-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='登录密码'),
        ),
    ]
