# Generated by Django 3.0.1 on 2020-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmanager', '0003_sysparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='编码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='参考价格')),
                ('verMain', models.CharField(max_length=20, null=True, verbose_name='主版本号')),
                ('verSub', models.CharField(max_length=20, null=True, verbose_name='最新版本号')),
                ('datePro', models.DateField(null=True, verbose_name='产品注册日期')),
                ('dateCur', models.DateField(null=True, verbose_name='版本发布日期')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '下架')], default=1, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
        ),
    ]
