# Generated by Django 3.0.1 on 2020-02-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysmanager', '0004_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('position', models.CharField(max_length=20, null=True, verbose_name='职位')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='电子邮箱')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '失效')], default=1, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='编码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('simpleName', models.CharField(max_length=50, verbose_name='简称')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='公司地址')),
                ('status', models.IntegerField(choices=[(1, '正常'), (0, '失效')], default=1, verbose_name='状态')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('contactPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysmanager.CusEmployee')),
                ('products', models.ManyToManyField(to='sysmanager.Products')),
            ],
        ),
        migrations.AddField(
            model_name='cusemployee',
            name='curCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysmanager.Customer'),
        ),
    ]
