# Generated by Django 3.0.1 on 2020-02-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('pClass', models.IntegerField(choices=[(1, '系统'), (2, '资料'), (3, '往来'), (4, '报表'), (0, '其他')], verbose_name='分类')),
                ('sValue', models.CharField(max_length=255, verbose_name='参数值')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='手机号码')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='电子邮箱')),
                ('loginPW', models.CharField(max_length=50, verbose_name='登录密码')),
                ('status', models.IntegerField(choices=[(0, '失效'), (1, '正常'), (2, '冻结')], default=1, verbose_name='状态')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPerson', to='baseinfo.Person', verbose_name='人员')),
            ],
        ),
    ]
