# Generated by Django 3.0.1 on 2020-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmanager', '0002_parameters_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='pClass',
            field=models.IntegerField(choices=[(1, '系统'), (2, '资料'), (3, '往来'), (4, '报表'), (99, '其他')], verbose_name='分类'),
        ),
    ]
