# Generated by Django 3.0.1 on 2020-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(default=None, max_length=50, verbose_name='确认密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userStatus',
            field=models.IntegerField(choices=[(0, '无效'), (1, '正常')], default=1, verbose_name='用户状态'),
        ),
    ]
