# Generated by Django 3.0.1 on 2020-03-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200302_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='re_password',
        ),
    ]
