# Generated by Django 3.0.1 on 2020-03-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_re_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imgName',
            field=models.CharField(max_length=255, null=True, verbose_name='头像文件名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liveCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveCity', to='backend.areaLever', verbose_name='居住城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liveProvince',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveProvince', to='backend.areaLever', verbose_name='居住省份'),
        ),
    ]
