# Generated by Django 3.0.1 on 2020-01-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='名称')),
                ('remark', models.CharField(max_length=64, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNumber', models.CharField(max_length=16, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('position', models.CharField(choices=[('product', '产品'), ('develop', '研发'), ('test', '测试'), ('service', '营运')], max_length=20, null=True, verbose_name='岗位')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='电子邮箱')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='手机号码')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSys.Department', verbose_name='部门')),
            ],
        ),
    ]
