# Generated by Django 3.0.1 on 2020-01-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobNumber', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
