# Generated by Django 3.0.1 on 2020-01-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pwd',
            field=models.CharField(max_length=32, null=True, verbose_name='登录密码'),
        ),
    ]
