# Generated by Django 3.0.1 on 2020-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSys', '0002_employee_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=1, verbose_name='状态'),
        ),
    ]
