# Generated by Django 3.0.1 on 2020-01-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSys', '0003_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='rPro',
            field=models.ManyToManyField(to='appSys.Project'),
        ),
    ]
