# Generated by Django 3.0.1 on 2020-02-10 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='relEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField(verbose_name='事件日期')),
                ('eventName', models.CharField(max_length=50, verbose_name='事件简称')),
                ('eventType', models.IntegerField(choices=[(1, '结婚'), (2, '生子'), (3, '周岁'), (4, '祝寿'), (5, '考学'), (6, '乔迁'), (7, '身故'), (0, '其他')], verbose_name='事件类型')),
                ('formType', models.IntegerField(choices=[(1, '隆重宴请'), (2, '亲朋小聚'), (3, '低调跳过'), (0, '待定')], verbose_name='宴请类型')),
                ('eventDes', models.CharField(max_length=255, null=True, verbose_name='事件说明')),
                ('direction', models.IntegerField(choices=[(1, '我发起'), (2, '他人发起')], verbose_name='事件发起方')),
                ('dateFrom', models.DateField(verbose_name='开始日期')),
                ('dateTo', models.DateField(verbose_name='截止日期')),
                ('amtOutFood', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='宴席支出金额')),
                ('amtOutOther', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='其他支出金额')),
                ('cntFamily', models.IntegerField(default=0, verbose_name='来宾户数')),
                ('cntTable', models.IntegerField(null=True, verbose_name='宴席桌数')),
                ('amtInBook', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='礼簿金额')),
                ('amtInOther', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='其他收入金额')),
                ('status', models.IntegerField(choices=[(1, '预测'), (2, '计划'), (9, '完成')], verbose_name='状态')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventFamily', to='baseinfo.Family', verbose_name='家庭')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventPerson', to='baseinfo.Person', verbose_name='事主')),
            ],
        ),
        migrations.CreateModel(
            name='joinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amtBook', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='礼金')),
                ('amtOther', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='其他支出')),
                ('recTime', models.TimeField(null=True, verbose_name='登记时间')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordEvent', to='business.relEvent', verbose_name='事件')),
                ('joinFamily', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familyJoin', to='baseinfo.Family', verbose_name='出席家庭')),
            ],
        ),
    ]
