# Generated by Django 3.0.1 on 2020-02-16 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysmanager', '0002_parameters_user'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='joinRecordUser', to='sysmanager.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='relevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relEventUser', to='sysmanager.User', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='joinrecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordEvent', to='business.RelEvent', verbose_name='事件'),
        ),
    ]
