# Generated by Django 3.0.1 on 2020-02-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200216_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordEvent', to='business.RelEvent', verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='relevent',
            name='eventType',
            field=models.IntegerField(choices=[(1, '结婚'), (2, '生子'), (3, '周岁'), (4, '祝寿'), (5, '考学'), (6, '乔迁'), (7, '身故'), (99, '其他')], verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='relevent',
            name='formType',
            field=models.IntegerField(choices=[(0, '待定'), (1, '隆重宴请'), (2, '亲朋小聚'), (3, '低调跳过')], verbose_name='宴请类型'),
        ),
    ]
