# Generated by Django 3.0.1 on 2020-02-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_auto_20200219_2032'),
        ('business', '0003_auto_20200216_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrecord',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordEvent', to='business.RelEvent', verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='joinrecord',
            name='recTime',
            field=models.DateTimeField(null=True, verbose_name='登记时间'),
        ),
        migrations.AlterField(
            model_name='relevent',
            name='formType',
            field=models.IntegerField(choices=[(1, '隆重宴请'), (2, '亲朋小聚'), (3, '低调跳过'), (99, '待定')], verbose_name='宴请类型'),
        ),
        migrations.AlterField(
            model_name='relevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventPerson', to='baseinfo.Person', verbose_name='当事人'),
        ),
    ]
